[package]
name = "websock-tungstenite-mux"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Native WebSocket multiplexing layer for logical streams"
repository = "https://github.com/foctal/websock"
readme = "../README.md"
keywords = ["network", "websocket", "multiplex", "native", "wasm"]
categories = ["network-programming", "web-programming"]
license = "MIT"

[dependencies]
bytes = { workspace = true }
thiserror = "2"
websock-proto = { workspace = true }
websock-mux-proto = { workspace = true }
tokio = { version = "1", features = ["rt", "sync", "macros"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["ring"]} 
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
rustls-native-certs = "0.8"
rcgen = "0.14"
rustls-pemfile = "2.2"
tokio-tungstenite = { version = "0.28", features = ["rustls-tls-webpki-roots"] }
futures-util = { version = "0.3" }
futures-core = { version = "0.3" }
futures-sink = { version = "0.3" }
tokio-util = { version = "0.7" }
#http = "1"
tracing = "0.1"
